// Copies the contents of a codeblock generated by Chroma syntax
// highlighter. Pass is the Id names of the surrounding code
// block / div and an Id name for ani interactive element that
// will inform the user the copy has occurred.

export async function copyCodeToClipboard(elementId: string, buttonId: string) {
  const ele = document.getElementById(elementId)
  const btn = document.getElementById(buttonId)
  console.log('ele= ' + elementId + '  btn= ' + buttonId)
  console.log(elementId.toString())
  console.log(buttonId.toString())

  if (ele != null && btn != null) {
    //    const innerEle = ele.querySelector(':last-child > .lntd > code')
    // TODO: This is pretty brittle. It relies on the structure of the code block
    // being exactly as it is. Maybe we should add a specific class to the inner
    // code element to make this more robust?

    const innerEle = ele.querySelector(':last-child > .chroma > code') as HTMLElement | null  
    console.log(innerEle)

    if (innerEle == null) {
      console.log(
        "Failed to copy the code block. Couldn't find the inner code element."
      )
      return
    }

    const codeToCopy = innerEle.innerText || innerEle.textContent || ''
    try {
      const result = await navigator.permissions.query({
        // NOTE: This is quiet TS hack to get around the fact that 'clipboard-write' is
        // not yet in the standard PermissionName type. It is supported in browsers,
        // but TypeScript doesn't know about it yet.
        // See https://github.com/microsoft/TypeScript/issues/31905
        name: 'clipboard-write' as PermissionName,
      })
      if (result.state == 'granted' || result.state == 'prompt') {
        await navigator.clipboard.writeText(codeToCopy)
      } else {
        console.log('Permission to write to clipboard not granted.')
      }
    } catch (error) {
      console.log(
        'Failed to copy the code block. Clipboard write permission not granted.'
      )
      console.error(error)
    } finally {
      codeWasCopied(btn)
    }
  } else {
    console.log("Failed to copy the code block. Id's weren't found.")
  }
}

// Interaction to let them know we copied the code for them.
// TODO: How about an animation?

function codeWasCopied(button: HTMLElement) {
  button.blur()
  button.innerText = 'Copied!'
  setTimeout(function () {
    button.innerText = 'Copy'
  }, 2000)
}
