// Copies the contents of a codeblock generated by Chroma syntax
// highlighter. Pass is the Id names of the surrounding code
// block / div and an Id name for ani interactive element that
// will inform the user the copy has occurred.

export async function copyCodeToClipboard(elementId: string, buttonId: string) {
  const eleRoot = document.getElementById(elementId)
  const eleButton = document.getElementById(buttonId)

  if (eleRoot != null && eleButton != null) {
    let eleInner: HTMLElement | null

    // Query is slightly different if the code block is inside a table.
    const isTables = eleRoot.querySelector<HTMLElement>('table')
    if (isTables) {
      eleInner = eleRoot.querySelector<HTMLElement>('.lntd:last-child code')
    } else {
      eleInner = eleRoot.querySelector<HTMLElement>('code')
    }

    // Make sure we found something.
    if (eleInner != null) {
      console.log(eleInner)

      // We're just going to concatenate the text content of all the
      // child elements of the code block.
      let codeToCopy: string = ''
      for (const child of eleInner.children) {
        codeToCopy = codeToCopy + (child.textContent || '')
      }

      //
      writeToClipboard(codeToCopy, eleButton)
    } else {
      console.error(
        "Failed to copy the code block. Couldn't find the inner code element."
      )
    }
  } else {
    console.error(
      "Failed to copy the code block. One or more elements weren't found by their Id's."
    )
  }
}

function writeToClipboard(newClip: string, eleButton: HTMLElement) {
  navigator.clipboard.writeText(newClip).then(
    () => {
      // Clipboard successfully set.
      codeCopySuccessful(eleButton)
    },
    () => {
      // Clipboard write failed.
      console.error('Failed to write to the clipboard.')
    }
  )
}

// Interaction to let them know we copied the code for them.
// TODO: How about an animation?

function codeCopySuccessful(eleButton: HTMLElement) {
  eleButton.blur()
  eleButton.innerText = 'Copied!'
  setTimeout(function () {
    eleButton.innerText = 'Copy'
  }, 2000)
}
