'use strict'

// Copies the contents of a codeblock generated by Chroma syntax
// highlighter. Pass is the Id names of the surrounding code
// block / div and an Id name for ani interactive element that
// will inform the user the copy has occurred.

export async function copyCodeToClipboard(elementId: string, buttonId: string) {
  const ele = document.getElementById(elementId)
  const btn = document.getElementById(buttonId)

  if (ele && btn) {
    const codeToCopy = ele.querySelector(':last-child > .lntd > code').innerText
    try {
      const result = await navigator.permissions.query({
        name: 'clipboard-write' as PermissionName,
      })
      if (result.state == 'granted' || result.state == 'prompt') {
        await navigator.clipboard.writeText(codeToCopy)
      } else {
        console.log('Permission to write to clipboard not granted.')
      }
    } catch (error) {
      console.error(error)
    } finally {
      codeWasCopied(btn)
    }
  } else {
    console.log("Failed to copy the code block. Id's weren't found.")
  }
}

// Interaction to let them know we copied the code for them.
// TODO: How about an animation?

export function codeWasCopied(button: HTMLElement) {
  button.blur()
  button.innerText = 'Copied!'
  setTimeout(function () {
    button.innerText = 'Copy'
  }, 2000)
}
